version: '3.7'

services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - freecodecamp:/var/lib/postgresql/data
    networks:
      - freecodecamp

volumes:
  freecodecamp:
    driver: local

networks:
  freecodecamp:
    driver: bridge
